CREATE TABLE tb_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    organization_id BIGINT REFERENCES tb_organizations(id),
    role_id BIGINT REFERENCES tb_roles(id),
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL
);